import {initializeApp} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import {getDatabase,ref,get} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js";
import {getAuth} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import {getFunctions,httpsCallable} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-functions.js";
const firebaseConfig={apiKey:"AIzaSyDWDaEZoZPwBe7wZX0aiDAGqs4b_EAkfgM",authDomain:"mingyue-stock.firebaseapp.com",databaseURL:"https://mingyue-stock-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"mingyue-stock",storageBucket:"mingyue-stock.firebasestorage.app",messagingSenderId:"774198660845",appId:"1:774198660845:web:93f4a725b6303aae9f86e4"};
const app=initializeApp(firebaseConfig);const db=getDatabase(app);const auth=getAuth(app);const functions=getFunctions(app,"asia-southeast1");const reviewFinancialRequest=httpsCallable(functions,"reviewFinancialRequest");
const ADMIN_EMAILS=["edisonkuo1030@gmail.com"];let withdrawals={},deposits={},users={},audit={};
const money=n=>"¥"+Number(n||0).toLocaleString("zh-TW",{minimumFractionDigits:2,maximumFractionDigits:2});const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function isAdmin(){const u=auth.currentUser||window.MingyueAuthBridge?.getUser?.()||window.MingyueAuth?.user||window.MingyueCurrentUser||null;return !!u&&ADMIN_EMAILS.includes(String(u.email||"").toLowerCase());}
async function load(){if(!isAdmin()){document.getElementById("admin-status").textContent="沒有管理員權限";return}const [w,d,u,a]=await Promise.all([get(ref(db,"withdrawalRequests")),get(ref(db,"depositRequests")),get(ref(db,"users")),get(ref(db,"adminAudit"))]);withdrawals=w.exists()?w.val():{};deposits=d.exists()?d.val():{};users=u.exists()?u.val():{};audit=a.exists()?a.val():{};document.getElementById("admin-status").textContent="管理員已驗證";render();}
function flat(o){const out=[];Object.entries(o||{}).forEach(([account,items])=>Object.entries(items||{}).forEach(([id,v])=>out.push({...v,id,accountId:v.accountId||account})));return out.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));}const pending=o=>flat(o).filter(x=>x.status==="pending");
function render(){const ws=pending(withdrawals),ds=pending(deposits);document.getElementById("stat-accounts").textContent=Object.keys(users).length;document.getElementById("stat-pending").textContent=ws.length;document.getElementById("stat-pending-deposit").textContent=ds.length;document.getElementById("stat-volume").textContent=money(ws.reduce((s,x)=>s+Number(x.amount||0),0)+ds.reduce((s,x)=>s+Number(x.amount||0),0));document.getElementById("withdrawal-list").innerHTML=listHTML(ws,"withdrawal");document.getElementById("deposit-list").innerHTML=listHTML(ds,"deposit");document.getElementById("account-list").innerHTML=Object.entries(users).map(([id,u])=>`<div class="row"><div><b>${esc(u.name||id)}</b><div class="meta">${esc(id)}</div></div><div class="amount">${money(u.balance)}<div class="meta">凍結 ${money(u.frozenBalance)}</div></div></div>`).join("")||'<div class="empty">沒有帳戶資料</div>';const aa=Object.values(audit).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));document.getElementById("audit-list").innerHTML=aa.map(x=>`<div class="row"><div><b>${esc(x.action)}</b><div class="meta">${esc(x.accountId||"")} · ${new Date(x.createdAt||0).toLocaleString("zh-TW")}</div></div><div>${money(x.amount||0)}</div></div>`).join("")||'<div class="empty">沒有操作紀錄</div>';}
function listHTML(items,type){if(!items.length)return '<div class="empty">目前沒有待審核項目</div>';return items.map(x=>`<div class="row"><div><b>${esc(x.accountId)}</b><div class="meta">${esc(x.id)} · ${new Date(x.createdAt||0).toLocaleString("zh-TW")}</div></div><div><div class="amount">${money(x.amount)}</div><div class="actions"><button class="approve" data-action="approve" data-type="${type}" data-account="${esc(x.accountId)}" data-id="${esc(x.id)}">核准</button><button class="reject" data-action="reject" data-type="${type}" data-account="${esc(x.accountId)}" data-id="${esc(x.id)}">駁回</button></div></div></div>`).join("");}
async function decide(type,account,id,decision){if(!isAdmin())return alert("沒有管理員權限");try{await reviewFinancialRequest({type,accountId:account,id,decision});await load();alert(decision==="approve"?"已核准並完成資金處理":"已駁回申請並完成資金回復");}catch(e){console.error(e);alert(e?.message||"後台處理失敗");}}
document.addEventListener("click",e=>{const b=e.target.closest("button[data-action]");if(b)decide(b.dataset.type,b.dataset.account,b.dataset.id,b.dataset.action==="approve"?"approve":"reject");const t=e.target.closest("button[data-tab]");if(t){document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));t.classList.add("active");document.querySelectorAll(".panel").forEach(x=>x.classList.add("hidden"));document.getElementById("panel-"+t.dataset.tab).classList.remove("hidden");}});document.querySelector('.tabs button[data-tab="withdrawals"]').classList.add("active");auth.onAuthStateChanged(()=>load().catch(e=>{console.error(e);document.getElementById("admin-status").textContent="Firebase 讀取失敗";}));
