import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getAuth, onAuthStateChanged, GoogleAuthProvider, signInWithPopup } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { getFunctions, httpsCallable } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-functions.js";
import { getDatabase, ref, get } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js";

const CONFIG={apiKey:"AIzaSyDWDaEZoZPwBe7wZX0aiDAGqs4b_EAkfgM",authDomain:"mingyue-stock.firebaseapp.com",databaseURL:"https://mingyue-stock-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"mingyue-stock",storageBucket:"mingyue-stock.firebasestorage.app",messagingSenderId:"774198660845",appId:"1:774198660845:web:93f4a725b6303aae9f86e4"};
const ADMIN_EMAIL="edisonkuo1030@gmail.com";
const app=getApps().length?getApp():initializeApp(CONFIG);
const auth=getAuth(app), db=getDatabase(app), functions=getFunctions(app,"asia-southeast1");
const callReview=httpsCallable(functions,"reviewFinancialRequest");
let withdrawals={},deposits={},users={},audit={};
const money=n=>"¥"+Number(n||0).toLocaleString("zh-TW",{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const flat=o=>Object.entries(o||{}).flatMap(([account,items])=>Object.entries(items||{}).map(([id,v])=>({...v,id,accountId:v.accountId||account}))).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));
const pending=o=>flat(o).filter(x=>x.status==="pending");
function setStatus(text){document.getElementById("admin-status").textContent=text;}
async function signIn(){try{await signInWithPopup(auth,new GoogleAuthProvider());}catch(e){console.error(e);setStatus(e?.message||"Google 登入失敗");}}
async function load(){const [w,d,u,a]=await Promise.all([get(ref(db,"withdrawalRequests")),get(ref(db,"depositRequests")),get(ref(db,"users")),get(ref(db,"adminAudit"))]);withdrawals=w.exists()?w.val():{};deposits=d.exists()?d.val():{};users=u.exists()?u.val():{};audit=a.exists()?a.val():{};render();}
function render(){const ws=pending(withdrawals),ds=pending(deposits);document.getElementById("stat-accounts").textContent=Object.keys(users).length;document.getElementById("stat-pending").textContent=ws.length;document.getElementById("stat-pending-deposit").textContent=ds.length;document.getElementById("stat-volume").textContent=money(ws.reduce((s,x)=>s+Number(x.amount||0),0)+ds.reduce((s,x)=>s+Number(x.amount||0),0));document.getElementById("withdrawal-list").innerHTML=listHTML(ws,"withdrawal");document.getElementById("deposit-list").innerHTML=listHTML(ds,"deposit");document.getElementById("account-list").innerHTML=Object.entries(users).map(([id,u])=>`<div class="row"><div><b>${esc(u.name||id)}</b><div class="meta">${esc(id)}</div></div><div class="amount">${money(u.balance)}<div class="meta">凍結 ${money(u.frozenBalance)}</div></div></div>`).join("")||'<div class="empty">沒有帳戶資料</div>';const aa=Object.values(audit).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));document.getElementById("audit-list").innerHTML=aa.map(x=>`<div class="row"><div><b>${esc(x.action)}</b><div class="meta">${esc(x.accountId||"")} · ${new Date(x.createdAt||0).toLocaleString("zh-TW")}</div></div><div>${money(x.amount||0)}</div></div>`).join("")||'<div class="empty">沒有操作紀錄</div>';}
function listHTML(items,type){if(!items.length)return '<div class="empty">目前沒有待審核項目</div>';return items.map(x=>`<div class="row"><div><b>${esc(x.accountId)}</b><div class="meta">${esc(x.id)} · ${new Date(x.createdAt||0).toLocaleString("zh-TW")}</div></div><div><div class="amount">${money(x.amount)}</div><div class="actions"><button class="approve" data-action="approve" data-type="${type}" data-account="${esc(x.accountId)}" data-id="${esc(x.id)}">核准</button><button class="reject" data-action="reject" data-type="${type}" data-account="${esc(x.accountId)}" data-id="${esc(x.id)}">駁回</button></div></div></div>`).join("");}
async function decide(type,accountId,id,decision){try{await callReview({type,accountId,id,decision});await load();alert(decision==="approve"?"已核准此金融申請。":"已駁回此金融申請。");}catch(e){console.error(e);alert(e?.message||"金融審核失敗，請稍後再試。");}}
document.addEventListener("click",e=>{if(e.target.closest("#admin-login"))return signIn();const b=e.target.closest("button[data-action]");if(b)decide(b.dataset.type,b.dataset.account,b.dataset.id,b.dataset.action==="approve"?"approve":"reject");const t=e.target.closest("button[data-tab]");if(t){document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));t.classList.add("active");document.querySelectorAll(".panel").forEach(x=>x.classList.add("hidden"));document.getElementById("panel-"+t.dataset.tab).classList.remove("hidden");}});
document.querySelector('.tabs button[data-tab="withdrawals"]').classList.add("active");
const login=document.createElement("button");login.id="admin-login";login.type="button";login.textContent="Google 管理員登入";login.style.cssText="margin-left:12px;padding:8px 12px;border:0;border-radius:8px;cursor:pointer";document.querySelector(".topbar").appendChild(login);
onAuthStateChanged(auth,async user=>{if(!user){setStatus("請先登入管理員 Google 帳號");return;}if(String(user.email||"").toLowerCase()!==ADMIN_EMAIL){setStatus("此帳號沒有金融後台權限");return;}setStatus("管理員已驗證 · Firebase 已連線");try{await load();}catch(e){console.error(e);setStatus("讀取金融資料失敗");}});
