import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getAuth, onAuthStateChanged, GoogleAuthProvider, signInWithPopup } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { getDatabase, ref, get, update } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js";
const CONFIG={apiKey:"AIzaSyDWDaEZoZPwBe7wZX0aiDAGqs4b_EAkfgM",authDomain:"mingyue-stock.firebaseapp.com",databaseURL:"https://mingyue-stock-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"mingyue-stock",storageBucket:"mingyue-stock.firebasestorage.app",messagingSenderId:"774198660845",appId:"1:774198660845:web:93f4a725b6303aae9f86e4"};
const ADMIN_EMAIL="edisonkuo1030@gmail.com";
const app=getApps().length?getApp():initializeApp(CONFIG),auth=getAuth(app),db=getDatabase(app);
let withdrawals={},deposits={},users={},audit={},stocks=[];
const money=n=>"¥"+Number(n||0).toLocaleString("zh-TW",{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const flat=o=>Object.entries(o||{}).flatMap(([account,items])=>Object.entries(items||{}).map(([id,v])=>({...v,id,accountId:v.accountId||account}))).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));
const pending=o=>flat(o).filter(x=>x.status==="pending");
function setStatus(text){document.getElementById("admin-status").textContent=text;}
async function signIn(){try{await signInWithPopup(auth,new GoogleAuthProvider());}catch(e){console.error(e);setStatus(e?.message||"Google 登入失敗");}}
async function load(){const [w,d,u,a,s]=await Promise.all([get(ref(db,"withdrawalRequests")),get(ref(db,"depositRequests")),get(ref(db,"users")),get(ref(db,"adminAudit")),get(ref(db,"stocks"))]);withdrawals=w.exists()?w.val():{};deposits=d.exists()?d.val():{};users=u.exists()?u.val():{};audit=a.exists()?a.val():{};const raw=s.exists()?s.val():[];stocks=Array.isArray(raw)?raw:Object.values(raw||{});render();}
function render(){const ws=pending(withdrawals),ds=pending(deposits);document.getElementById("stat-accounts").textContent=Object.keys(users).length;document.getElementById("stat-pending").textContent=ws.length;document.getElementById("stat-pending-deposit").textContent=ds.length;document.getElementById("stat-volume").textContent=money(ws.reduce((s,x)=>s+Number(x.amount||0),0)+ds.reduce((s,x)=>s+Number(x.amount||0),0));document.getElementById("withdrawal-list").innerHTML=listHTML(ws,"withdrawal");document.getElementById("deposit-list").innerHTML=listHTML(ds,"deposit");document.getElementById("account-list").innerHTML=Object.entries(users).map(([id,u])=>`<div class="row"><div><b>${esc(u.name||id)}</b><div class="meta">${esc(id)}</div></div><div class="amount">${money(u.balance)}<div class="meta">凍結 ${money(u.frozenBalance)}</div></div></div>`).join("")||'<div class="empty">沒有帳戶資料</div>';const aa=Object.values(audit).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));document.getElementById("audit-list").innerHTML=aa.map(x=>`<div class="row"><div><b>${esc(x.action)}</b><div class="meta">${esc(x.accountId||x.stockId||"")} · ${new Date(x.createdAt||0).toLocaleString("zh-TW")}</div></div><div>${x.amount!=null?money(x.amount):x.newPrice!=null?money(x.newPrice):""}</div></div>`).join("")||'<div class="empty">沒有操作紀錄</div>';renderStocks();}
function listHTML(items,type){if(!items.length)return '<div class="empty">目前沒有待審核項目</div>';return items.map(x=>`<div class="row"><div><b>${esc(x.accountId)}</b><div class="meta">${esc(x.id)} · ${new Date(x.createdAt||0).toLocaleString("zh-TW")}</div></div><div><div class="amount">${money(x.amount)}</div><div class="actions"><button class="approve" data-action="approve" data-type="${type}" data-account="${esc(x.accountId)}" data-id="${esc(x.id)}">核准</button><button class="reject" data-action="reject" data-type="${type}" data-account="${esc(x.accountId)}" data-id="${esc(x.id)}">駁回</button></div></div></div>`).join("");}
function renderStocks(){const box=document.getElementById("stock-list");if(!box)return;if(!stocks.length){box.innerHTML='<div class="empty">目前沒有股票資料</div>';return;}box.innerHTML=stocks.map((s,i)=>{const id=String(s.id||s.code||i);return `<div class="stock-admin-row"><div class="stock-admin-info"><b>${esc(s.name||id)}</b><div class="meta">${esc(id)} · ${esc(s.industry||"未分類")}</div></div><div class="stock-admin-fields"><label>現價<input data-stock-field="price" data-stock-index="${i}" type="number" min="0.01" step="0.01" value="${Number(s.price||0)}"></label><label>前收<input data-stock-field="previous" data-stock-index="${i}" type="number" min="0.01" step="0.01" value="${Number(s.previous??s.price??0)}"></label><label>成交量<input data-stock-field="volume" data-stock-index="${i}" type="number" min="0" step="1" value="${Number(s.volume||0)}"></label><button class="approve" data-stock-save="${i}">更新</button></div></div>`;}).join("");}
async function saveStock(index){try{if(!auth.currentUser||String(auth.currentUser.email||"").toLowerCase()!==ADMIN_EMAIL)throw new Error("沒有管理員權限");const s={...(stocks[index]||{})};const fields=[...document.querySelectorAll(`input[data-stock-index="${index}"]`)];const price=Number(fields.find(x=>x.dataset.stockField==="price")?.value),previous=Number(fields.find(x=>x.dataset.stockField==="previous")?.value),volume=Number(fields.find(x=>x.dataset.stockField==="volume")?.value);if(!Number.isFinite(price)||price<=0)throw new Error("股價必須大於 0");if(!Number.isFinite(previous)||previous<=0)throw new Error("前收必須大於 0");if(!Number.isFinite(volume)||volume<0)throw new Error("成交量不可小於 0");const oldPrice=Number(s.price||0);s.price=Number(price.toFixed(2));s.previous=Number(previous.toFixed(2));s.volume=Math.floor(volume);stocks[index]=s;const auditId=`AUD-STOCK-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const updates={stocks};updates[`adminAudit/${auditId}`]={action:"stock:adjust",stockId:String(s.id||s.code||index),stockName:s.name||s.id||String(index),oldPrice,newPrice:s.price,previous:s.previous,volume:s.volume,adminId:auth.currentUser.uid,createdAt:Date.now()};await update(ref(db),updates);renderStocks();alert(`${s.name||s.id||"股票"} 已更新。`);}catch(e){console.error(e);alert(e?.message||"股票更新失敗，請稍後再試。");}}
async function decide(type,accountId,id,decision){try{if(!auth.currentUser||String(auth.currentUser.email||"").toLowerCase()!==ADMIN_EMAIL)throw new Error("沒有管理員權限");const requestPath=`${type==="withdrawal"?"withdrawalRequests":"depositRequests"}/${accountId}/${id}`;const [requestSnap,userSnap]=await Promise.all([get(ref(db,requestPath)),get(ref(db,`users/${accountId}`))]);if(!requestSnap.exists())throw new Error("申請不存在");if(!userSnap.exists())throw new Error("帳戶不存在");const req=requestSnap.val(),user=userSnap.val();if(req.status!=="pending")throw new Error("這筆申請已經處理");const amount=Number(req.amount);if(!Number.isFinite(amount)||amount<=0)throw new Error("申請金額無效");let balance=Number(user.balance||0),frozen=Number(user.frozenBalance||0);if(type==="withdrawal"){if(frozen<amount)throw new Error("凍結金額不足");if(decision==="reject")balance+=amount;frozen-=amount;}else if(decision==="approve"){balance+=amount;}const status=decision==="approve"?"approved":"rejected",adminId=auth.currentUser.uid,txId=`TX-${Date.now()}-${Math.random().toString(36).slice(2,10)}`,auditId=`AUD-${Date.now()}-${Math.random().toString(36).slice(2,10)}`,now=Date.now(),updates={};updates[`users/${accountId}/balance`]=balance;updates[`users/${accountId}/frozenBalance`]=frozen;updates[`${requestPath}/status`]=status;updates[`${requestPath}/reviewedAt`]=now;updates[`${requestPath}/reviewedBy`]=adminId;updates[`fundTransactions/${accountId}/${txId}`]={type:`${type}_${status}`,amount,balanceAfter:balance,requestId:id,createdAt:now,adminId};updates[`adminAudit/${auditId}`]={action:`${type}:${status}`,accountId,requestId:id,amount,adminId,createdAt:now};await update(ref(db),updates);await load();alert(decision==="approve"?"已核准此金融申請。":"已駁回此金融申請。");}catch(e){console.error(e);alert(e?.message||"金融審核失敗，請稍後再試。");}}
document.addEventListener("click",e=>{if(e.target.closest("#admin-login"))return signIn();const sb=e.target.closest("[data-stock-save]");if(sb)return saveStock(Number(sb.dataset.stockSave));const b=e.target.closest("button[data-action]");if(b)return decide(b.dataset.type,b.dataset.account,b.dataset.id,b.dataset.action==="approve"?"approve":"reject");const t=e.target.closest("button[data-tab]");if(t){document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));t.classList.add("active");document.querySelectorAll(".panel").forEach(x=>x.classList.add("hidden"));document.getElementById("panel-"+t.dataset.tab).classList.remove("hidden");}});
document.querySelector('.tabs button[data-tab="stocks"]').classList.add("active");
const login=document.createElement("button");login.id="admin-login";login.type="button";login.textContent="Google 管理員登入";login.style.cssText="margin-left:12px;padding:8px 12px;border:0;border-radius:8px;cursor:pointer";document.querySelector(".topbar").appendChild(login);
onAuthStateChanged(auth,async user=>{if(!user){setStatus("請先登入管理員 Google 帳號");return;}if(String(user.email||"").toLowerCase()!==ADMIN_EMAIL){setStatus("此 Google 帳號沒有管理員權限");return;}if(user.emailVerified!==true){setStatus("此帳號尚未完成 Google 帳號驗證");return;}setStatus("管理員已驗證 · Firebase 已連線");try{await load();}catch(e){console.error(e);setStatus("讀取金融資料失敗");}});
