import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { getDatabase, ref, get, set, update, remove, onValue, push } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js";

const firebaseConfig={apiKey:"AIzaSyDWDaEZoZPwBe7wZX0aiDAGqs4b_EAkfgM",authDomain:"mingyue-stock.firebaseapp.com",databaseURL:"https://mingyue-stock-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"mingyue-stock",storageBucket:"mingyue-stock.firebasestorage.app",messagingSenderId:"774198660845",appId:"1:774198660845:web:93f4a725b6303aae9f86e4",measurementId:"G-Z7F6N0ZJYJ"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),provider=new GoogleAuthProvider();
const $=id=>document.getElementById(id);
let data={stocks:[],companies:[],news:[],users:{},portfolios:{},transactions:{},history:{},system:{},depositRequests:{},ipoRequests:{}};
let currentUser=null,isAdmin=false,stopLive=null;
function toast(msg){const el=$("toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function money(v){return "¥"+Number(v||0).toLocaleString("zh-TW",{minimumFractionDigits:2,maximumFractionDigits:2})}
function now(){return new Date().toLocaleString("zh-TW",{hour12:false})}
async function checkAdmin(user){const snap=await get(ref(db,"admins/"+user.uid));return snap.exists()&&(snap.val()===true||snap.val()?.active===true||snap.val()?.role==="admin")}
async function login(){$("loginStatus").textContent="正在開啟 Google 登入…";try{await signInWithPopup(auth,provider)}catch(e){console.error(e);$("loginStatus").textContent="登入失敗："+(e?.message||"未知錯誤")}}
async function boot(user){currentUser=user;try{isAdmin=await checkAdmin(user)}catch(e){console.error(e);isAdmin=false}if(!isAdmin){$("loginStatus").textContent=`這個 Google 帳號不是管理員。你的 UID：${user.uid}`;await signOut(auth);return}$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('adminEmail').textContent=user.email||user.displayName||user.uid;$('adminInfo').innerHTML=`<div class="info-item"><small>Google 帳號</small><strong>${esc(user.email||"—")}</strong></div><div class="info-item"><small>UID</small><strong>${esc(user.uid)}</strong></div><div class="info-item"><small>權限</small><strong>Administrator</strong></div>`;subscribe()}
function subscribe(){if(stopLive)stopLive();stopLive=onValue(ref(db),snap=>{data=snap.val()||{};data.stocks=Array.isArray(data.stocks)?data.stocks:[];data.companies=Array.isArray(data.companies)?data.companies:[];data.news=Array.isArray(data.news)?data.news:[];data.users=data.users&&typeof data.users==="object"?data.users:{};data.portfolios=data.portfolios||{};data.transactions=data.transactions||{};data.history=data.history||{};data.system=data.system||{};data.depositRequests=data.depositRequests||{};data.ipoRequests=data.ipoRequests||{};renderAll();renderApprovals();$('connectionBadge').textContent='Firebase 已連線'})}
function emptyRow(cols,msg){return `<tr><td colspan="${cols}">${msg}</td></tr>`}
function statusText(v){return v==='approved'?'已核准':v==='rejected'?'已拒絕':'待審核'}
function requestStatusClass(v){return v==='approved'?'ok':v==='rejected'?'bad':'pending'}
function renderApprovals(){const dr=Object.entries(data.depositRequests||{}).sort((a,b)=>Number(b[1]?.createdAt||0)-Number(a[1]?.createdAt||0));const ir=Object.entries(data.ipoRequests||{}).sort((a,b)=>Number(b[1]?.createdAt||0)-Number(a[1]?.createdAt||0));const dt=$('depositRequestsTable'),it=$('ipoRequestsTable');if(dt)dt.innerHTML=dr.map(([id,r])=>`<tr><td>${esc(new Date(Number(r.createdAt||Date.now())).toLocaleString('zh-TW',{hour12:false}))}</td><td><b>${esc(r.accountId||r.uid||'—')}</b></td><td>${money(r.amount)}</td><td><span class="request-status ${requestStatusClass(r.status)}">${statusText(r.status)}</span></td><td class="actions">${r.status==='pending'?`<button class="mini edit" data-action="deposit-approve" data-id="${esc(id)}">核准</button><button class="mini delete" data-action="deposit-reject" data-id="${esc(id)}">拒絕</button>`:'—'}</td></tr>`).join('')||emptyRow(5,'目前沒有儲值申請');if(it)it.innerHTML=ir.map(([id,r])=>`<tr><td>${esc(new Date(Number(r.createdAt||Date.now())).toLocaleString('zh-TW',{hour12:false}))}</td><td>${esc(r.companyName||'—')}</td><td><b>${esc(r.code||'—')}</b></td><td>${money(r.capital)}</td><td><span class="request-status ${requestStatusClass(r.status)}">${statusText(r.status)}</span></td><td class="actions">${r.status==='pending'?`<button class="mini edit" data-action="ipo-approve" data-id="${esc(id)}">核准上市</button><button class="mini delete" data-action="ipo-reject" data-id="${esc(id)}">拒絕</button>`:'—'}</td></tr>`).join('')||emptyRow(6,'目前沒有 IPO 申請')}
function renderAll(){$('statStocks').textContent=data.stocks.length;$('statCompanies').textContent=data.companies.length;$('statNews').textContent=data.news.length;$('statUsers').textContent=Object.keys(data.users).length;$('stocksTable').innerHTML=data.stocks.map((s,i)=>`<tr><td><b>${esc(s.id)}</b></td><td>${esc(s.name)}</td><td>${esc(s.industry)}</td><td>${money(s.price)}</td><td>${money(s.previous)}</td><td>${Number(s.volume||0).toLocaleString()}</td><td class="actions"><button class="mini edit" data-action="stock-edit" data-i="${i}">編輯</button><button class="mini delete" data-action="stock-delete" data-i="${i}">刪除</button></td></tr>`).join('')||emptyRow(7,'目前沒有股票');$('companiesTable').innerHTML=data.companies.map((c,i)=>`<tr><td><b>${esc(c.code)}</b></td><td>${esc(c.shortName||c.name)}</td><td>${esc(c.industry)}</td><td>${money(c.capital)}</td><td>${esc(c.status||'—')}</td><td>${c.listed?'是':'否'}</td><td class="actions"><button class="mini edit" data-action="company-edit" data-i="${i}">編輯</button><button class="mini delete" data-action="company-delete" data-i="${i}">刪除</button></td></tr>`).join('')||emptyRow(7,'目前沒有公司');$('newsList').innerHTML=data.news.slice().reverse().map((n,ri)=>{const i=data.news.length-1-ri;return `<article class="news-card"><small>${esc(n.companyName||n.companyCode||'明月證券')} · ${esc(n.time||'')}</small><h3>${esc(n.title)}</h3><p>${esc(n.content)}</p><div class="actions"><button class="mini edit" data-action="news-edit" data-i="${i}">編輯</button><button class="mini delete" data-action="news-delete" data-i="${i}">刪除</button></div></article>`}).join('')||"<div class='activity'>目前沒有新聞。</div>";$('usersTable').innerHTML=Object.entries(data.users).map(([id,u])=>`<tr><td><b>${esc(id)}</b></td><td>${esc(u?.name||'—')}</td><td>${money(u?.balance)}</td><td class="actions"><button class="mini edit" data-action="user-edit" data-id="${esc(id)}">調整餘額</button></td></tr>`).join('')||emptyRow(4,'目前沒有使用者');$('marketEnabled').checked=data.system.marketEnabled!==false;$('systemMessage').value=data.system.message||'';$('activityList').innerHTML=`<div class="activity">資料最後同步：${esc(now())}</div><div class="activity">管理員：${esc(currentUser?.email||currentUser?.uid||'—')}</div><div class="activity">股票 ${data.stocks.length} · 公司 ${data.companies.length} · 新聞 ${data.news.length} · 使用者 ${Object.keys(data.users).length}</div>`}
function switchSection(name){document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section===name))}
function openModal(title,html,submit){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden');$('modalBody').querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();submit(new FormData(e.target))})}
function closeModal(){$('modal').classList.add('hidden')}
async function log(action,target){try{const r=push(ref(db,'adminLogs'));await set(r,{action,target,adminUid:currentUser.uid,adminEmail:currentUser.email||'',time:now()})}catch(e){console.warn(e)}}
function stockForm(s={}){return `<form><div class="form-grid"><div class="field"><label>股票代號</label><input name="id" value="${esc(s.id)}" required></div><div class="field"><label>股票名稱</label><input name="name" value="${esc(s.name)}" required></div><div class="field"><label>公司</label><input name="company" value="${esc(s.company||s.name)}"></div><div class="field"><label>產業</label><input name="industry" value="${esc(s.industry)}"></div><div class="field"><label>類型</label><input name="type" value="${esc(s.type||'')}"></div><div class="field"><label>目前價格</label><input name="price" type="number" step="0.01" value="${Number(s.price||0)}" required></div><div class="field"><label>昨收</label><input name="previous" type="number" step="0.01" value="${Number(s.previous||0)}" required></div><div class="field"><label>成交量</label><input name="volume" type="number" value="${Number(s.volume||0)}"></div><div class="field"><label>資本額</label><input name="capital" type="number" value="${Number(s.capital||0)}"></div><div class="field"><label>股數</label><input name="shares" type="number" value="${Number(s.shares||0)}"></div></div><div class="modal-actions"><button type="button" class="ghost" id="cancelBtn">取消</button><button class="primary">儲存</button></div></form>`}
function companyForm(c={}){return `<form><div class="form-grid"><div class="field"><label>公司代號</label><input name="code" value="${esc(c.code)}" required></div><div class="field"><label>公司名稱</label><input name="name" value="${esc(c.name)}" required></div><div class="field"><label>簡稱</label><input name="shortName" value="${esc(c.shortName)}"></div><div class="field"><label>產業</label><input name="industry" value="${esc(c.industry)}"></div><div class="field"><label>資本額</label><input name="capital" type="number" value="${Number(c.capital||0)}"></div><div class="field"><label>所有人</label><input name="ownerName" value="${esc(c.ownerName)}"></div><div class="field"><label>企業狀態</label><input name="status" value="${esc(c.status)}"></div><div class="field"><label>上市狀態</label><select name="listed"><option value="true" ${c.listed!==false?'selected':''}>已上市</option><option value="false" ${c.listed===false?'selected':''}>未上市</option></select></div></div><div class="modal-actions"><button type="button" class="ghost" id="cancelBtn">取消</button><button class="primary">儲存</button></div></form>`}
function newsForm(n={}){return `<form><div class="field"><label>公司</label><input name="companyName" value="${esc(n.companyName||'')}" placeholder="例如：明月鐵路"></div><div class="field"><label>標題</label><input name="title" value="${esc(n.title||'')}" required></div><div class="field"><label>內容</label><textarea name="content" required>${esc(n.content||'')}</textarea></div><div class="modal-actions"><button type="button" class="ghost" id="cancelBtn">取消</button><button class="primary">發布</button></div></form>`}
function userForm(id,u){return `<form><div class="field"><label>帳號</label><input value="${esc(id)}" disabled></div><div class="field"><label>名稱</label><input value="${esc(u?.name||'')}" disabled></div><div class="field"><label>新的證券餘額</label><input name="balance" type="number" step="0.01" value="${Number(u?.balance||0)}" required></div><div class="modal-actions"><button type="button" class="ghost" id="cancelBtn">取消</button><button class="primary">套用</button></div></form>`}
function bindCancel(){$('cancelBtn')?.addEventListener('click',closeModal)}
function openStock(index=null){const old=index===null?{}:data.stocks[index];openModal(index===null?'新增股票':'編輯股票',stockForm(old),async fd=>{const obj={...old,id:fd.get('id').trim().toUpperCase(),name:fd.get('name').trim(),company:fd.get('company').trim(),industry:fd.get('industry').trim(),type:fd.get('type').trim(),price:Number(fd.get('price')),previous:Number(fd.get('previous')),volume:Number(fd.get('volume')),capital:Number(fd.get('capital')),shares:Number(fd.get('shares'))};if(!obj.id||!obj.name||!Number.isFinite(obj.price)){toast('資料不完整');return}const arr=[...data.stocks];if(index===null)arr.push(obj);else arr[index]=obj;await set(ref(db,'stocks'),arr);await log(index===null?'新增股票':'修改股票',obj.id);closeModal();toast('股票已儲存')});bindCancel()}
async function deleteStock(i){if(!confirm(`確定刪除 ${data.stocks[i]?.name||data.stocks[i]?.id}？`))return;const arr=[...data.stocks];const id=arr[i]?.id;arr.splice(i,1);await set(ref(db,'stocks'),arr);await log('刪除股票',id);toast('已刪除')}
function openCompany(index=null){const old=index===null?{}:data.companies[index];openModal(index===null?'新增公司':'編輯公司',companyForm(old),async fd=>{const obj={...old,id:old.id||(`${fd.get('code')}-COMPANY`),code:fd.get('code').trim().toUpperCase(),name:fd.get('name').trim(),shortName:fd.get('shortName').trim(),industry:fd.get('industry').trim(),capital:Number(fd.get('capital')),ownerName:fd.get('ownerName').trim(),status:fd.get('status').trim(),listed:fd.get('listed')==='true',ipoStatus:fd.get('listed')==='true'?'已上市':'未上市',createdAt:old.createdAt||new Date().toLocaleDateString('zh-TW')};const arr=[...data.companies];if(index===null)arr.push(obj);else arr[index]=obj;await set(ref(db,'companies'),arr);await log(index===null?'新增公司':'修改公司',obj.code);closeModal();toast('公司已儲存')});bindCancel()}
async function deleteCompany(i){if(!confirm(`確定刪除 ${data.companies[i]?.shortName||data.companies[i]?.code}？`))return;const arr=[...data.companies];const id=arr[i]?.code;arr.splice(i,1);await set(ref(db,'companies'),arr);await log('刪除公司',id);toast('已刪除')}
function openNews(index=null){const old=index===null?{}:data.news[index];openModal(index===null?'發布新聞':'編輯新聞',newsForm(old),async fd=>{const obj={...old,id:old.id||Date.now(),companyName:fd.get('companyName').trim()||'明月證券',title:fd.get('title').trim(),content:fd.get('content').trim(),time:now(),category:old.category||'admin',author:'明月證券管理後臺',authorType:'admin'};const arr=[...data.news];if(index===null)arr.push(obj);else arr[index]=obj;await set(ref(db,'news'),arr);await log(index===null?'發布新聞':'修改新聞',obj.title);closeModal();toast('新聞已發布')});bindCancel()}
async function deleteNews(i){if(!confirm('確定刪除此新聞？'))return;const arr=[...data.news];const title=arr[i]?.title;arr.splice(i,1);await set(ref(db,'news'),arr);await log('刪除新聞',title);toast('已刪除')}
function openUser(id){const u=data.users[id]||{};openModal('調整使用者餘額',userForm(id,u),async fd=>{const balance=Number(fd.get('balance'));if(!Number.isFinite(balance)||balance<0){toast('餘額無效');return}await update(ref(db,'users/'+id),{balance});await log('調整餘額',id);closeModal();toast('餘額已更新')});bindCancel()}
async function approveDeposit(id){const r=data.depositRequests?.[id];if(!r||r.status!=='pending')return;const uid=r.accountId||r.uid,amount=Number(r.amount);if(!uid||!Number.isFinite(amount)||amount<=0){toast('申請資料無效');return}if(!confirm(`核准儲值 ${money(amount)}？\n帳號：${uid}`))return;const snap=await get(ref(db,'users/'+uid));const u=snap.exists()?snap.val():{};const old=Number(u.balance||0);await update(ref(db),{['users/'+uid+'/balance']:old+amount,['depositRequests/'+id+'/status']:'approved',['depositRequests/'+id+'/approvedAt']:Date.now(),['depositRequests/'+id+'/approvedBy']:currentUser.uid});await log('核准儲值',`${uid} ${amount}`);toast('儲值已核准')}
async function rejectDeposit(id){const r=data.depositRequests?.[id];if(!r||r.status!=='pending')return;if(!confirm('確定拒絕這筆儲值申請？'))return;await update(ref(db,'depositRequests/'+id),{status:'rejected',rejectedAt:Date.now(),rejectedBy:currentUser.uid});await log('拒絕儲值',id);toast('已拒絕儲值申請')}
async function approveIpo(id){const r=data.ipoRequests?.[id];if(!r||r.status!=='pending')return;const code=r.code,companies=[...(data.companies||[])],ci=companies.findIndex(c=>c.code===code);if(ci<0){toast('找不到公司');return}const c={...companies[ci]};if(c.listed){await update(ref(db,'ipoRequests/'+id),{status:'approved',approvedAt:Date.now(),approvedBy:currentUser.uid});toast('公司已上市');return}if(!confirm(`核准 ${c.shortName||c.name}（${code}）上市？`))return;c.listed=true;c.ipoStatus='已上市';c.status='上市公司';c.listedAt=new Date().toLocaleString('zh-TW',{hour12:false});const stocks=[...(data.stocks||[])];if(!stocks.some(s=>s.id===code)){const shares=Math.max(1000000,Math.floor(Number(c.capital||0)/10));const price=Number((Number(c.capital||0)/shares).toFixed(2));stocks.push({id:code,name:c.shortName||c.name,company:c.name,industry:c.industry||'',type:'上市公司',price,previous:price,volume:0,capital:Number(c.capital||0),shares})}await update(ref(db),{companies,stocks,['ipoRequests/'+id+'/status']:'approved',['ipoRequests/'+id+'/approvedAt']:Date.now(),['ipoRequests/'+id+'/approvedBy']:currentUser.uid});await log('核准IPO',code);toast(`${c.shortName||c.name} 已上市`)}
async function rejectIpo(id){const r=data.ipoRequests?.[id];if(!r||r.status!=='pending')return;if(!confirm('確定拒絕這筆 IPO 申請？'))return;await update(ref(db,'ipoRequests/'+id),{status:'rejected',rejectedAt:Date.now(),rejectedBy:currentUser.uid});if(r.code){const companies=[...(data.companies||[])],i=companies.findIndex(c=>c.code===r.code);if(i>=0){companies[i]={...companies[i],ipoStatus:'未通過'};await set(ref(db,'companies'),companies)}}await log('拒絕IPO',r.code||id);toast('已拒絕 IPO 申請')}
async function saveSettings(){await update(ref(db,'system'),{marketEnabled:$('marketEnabled').checked,message:$('systemMessage').value.trim(),updatedAt:now(),updatedBy:currentUser.uid});await log('修改系統設定','system');toast('系統設定已儲存')}
document.addEventListener('click',e=>{const nav=e.target.closest('.nav');if(nav)switchSection(nav.dataset.section);const a=e.target.closest('[data-action]');if(!a)return;const i=a.dataset.i;switch(a.dataset.action){case'stock-edit':openStock(Number(i));break;case'stock-delete':deleteStock(Number(i));break;case'company-edit':openCompany(Number(i));break;case'company-delete':deleteCompany(Number(i));break;case'news-edit':openNews(Number(i));break;case'news-delete':deleteNews(Number(i));break;case'user-edit':openUser(a.dataset.id);break;case'deposit-approve':approveDeposit(a.dataset.id);break;case'deposit-reject':rejectDeposit(a.dataset.id);break;case'ipo-approve':approveIpo(a.dataset.id);break;case'ipo-reject':rejectIpo(a.dataset.id);break}});
$('googleLoginBtn').addEventListener('click',login);$('logoutBtn').addEventListener('click',()=>signOut(auth));$('modalClose').addEventListener('click',closeModal);$('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('addStockBtn').addEventListener('click',()=>openStock());$('addCompanyBtn').addEventListener('click',()=>openCompany());$('addNewsBtn').addEventListener('click',()=>openNews());$('saveSettingsBtn').addEventListener('click',saveSettings);$('refreshBtn').addEventListener('click',async()=>{const s=await get(ref(db));data=s.val()||{};renderAll();renderApprovals();toast('資料已重新讀取')});$('refreshApprovalsBtn')?.addEventListener('click',async()=>{const s=await get(ref(db));data=s.val()||{};renderAll();renderApprovals();toast('審核資料已重新讀取')});
onAuthStateChanged(auth,user=>{if(user)boot(user);else{$('appView').classList.add('hidden');$('loginView').classList.remove('hidden');currentUser=null;isAdmin=false}});
