/* 明月證券 v4.4 Approval Bridge：儲值與 IPO 均需後臺審核 */
import { getApps } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { getDatabase, ref, get, push, set } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js";
const app=getApps()[0],auth=getAuth(app),db=getDatabase(app);
function uid(){return auth.currentUser?.uid||localStorage.getItem("mingyue_current_google_uid")||localStorage.getItem("mingyue_active_account_id")||null}
function toast(m){typeof window.showToast==="function"?window.showToast(m):alert(m)}
function closeDeposit(){document.getElementById("deposit-modal")?.classList.remove("show")}
function openDeposit(){const m=document.getElementById("deposit-modal");if(!m)return toast("找不到儲值視窗");const i=document.getElementById("deposit-amount");if(i)i.value="";const w=document.getElementById("deposit-wallet");if(w)w.textContent="提交後等待管理員審核";const t=m.querySelector("h3");if(t)t.textContent="💰 證券儲值申請";const d=m.querySelector(".modal-header p");if(d)d.textContent="送出後不會立即增加餘額，必須由管理員核准。";m.classList.add("show")}
async function submitDeposit(){const amount=Number(document.getElementById("deposit-amount")?.value),accountId=uid();if(!accountId)return toast("請先完成 Google 登入，再申請儲值");if(!Number.isFinite(amount)||amount<=0)return toast("請輸入有效儲值金額");const snap=await get(ref(db,"depositRequests"));let duplicate=false;if(snap.exists())snap.forEach(x=>{const r=x.val();if(r?.accountId===accountId&&r?.status==="pending")duplicate=true});if(duplicate)return toast("你已有一筆待審核的儲值申請");const r=push(ref(db,"depositRequests"));await set(r,{accountId,uid:accountId,amount,status:"pending",createdAt:Date.now(),createdBy:accountId});closeDeposit();toast(`儲值申請 ${amount.toLocaleString()} 已送出，等待後臺審核`)}
async function submitIPO(code){const accountId=uid();if(!accountId)return toast("請先完成 Google 登入");const snap=await get(ref(db,"companies"));const companies=snap.exists()&&Array.isArray(snap.val())?snap.val():[];const company=companies.find(c=>c.code===code&&c.owner===accountId);if(!company)return toast("找不到這家公司或你不是公司負責人");if(company.listed)return toast("這家公司已經上市");if(company.ipoStatus==="審核中")return toast("IPO 已在審核中");if(Number(company.capital)<10000000)return toast("註冊資本不足 ¥10,000,000");const pending=await get(ref(db,"ipoRequests"));let duplicate=false;if(pending.exists())pending.forEach(x=>{const r=x.val();if(r?.code===code&&r?.owner===accountId&&r?.status==="pending")duplicate=true});if(duplicate)return toast("這家公司已有待審核的 IPO 申請");if(!confirm(`確定申請「${company.name}」IPO？\n\n送出後必須由明月證券管理後臺核准，核准後才會正式上市。`))return;const req=push(ref(db,"ipoRequests"));await set(req,{companyId:company.id,code:company.code,companyName:company.name,shortName:company.shortName||company.name,capital:Number(company.capital||0),owner:accountId,status:"pending",createdAt:Date.now(),createdBy:accountId});toast("IPO 申請已送出，等待管理員審核");if(typeof window.showPage==="function")window.showPage("company")}
window.openDepositModal=openDeposit;window.openDeposit=openDeposit;window.deposit=submitDeposit;window.depositMoney=submitDeposit;window.confirmDeposit=submitDeposit;window.applyIPO=submitIPO;window.approveIPO=()=>toast("IPO 必須由管理後臺核准");
onAuthStateChanged(auth,u=>{if(u){localStorage.setItem("mingyue_current_google_uid",u.uid);localStorage.setItem("mingyue_active_account_id",u.uid)}});
console.log("明月證券 v4.4 Approval Bridge 已載入");
