/* Mingyue Securities v4.4.1 Approval Bridge */
import { getApps } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { getDatabase, ref, get, push, set, onValue } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js";
const app=getApps()[0],auth=getAuth(app),db=getDatabase(app);
const uid=()=>auth.currentUser?.uid||localStorage.getItem("mingyue_current_google_uid")||localStorage.getItem("mingyue_active_account_id")||null;
const toast=m=>typeof window.showToast==="function"?window.showToast(m):alert(m);
const list=v=>Array.isArray(v)?v.filter(Boolean):(v&&typeof v==="object"?Object.values(v).filter(Boolean):[]);
const map=v=>{if(v&&typeof v==="object"&&!Array.isArray(v))return {...v};const r={};if(Array.isArray(v))v.forEach(x=>{if(x?.code)r[x.code]=x});return r};
function openDeposit(){const m=document.getElementById("deposit-modal");if(!m)return toast("找不到儲值視窗");const i=document.getElementById("deposit-amount");if(i)i.value="";const w=document.getElementById("deposit-wallet");if(w)w.textContent="提交後等待管理員審核";const h=m.querySelector("h3");if(h)h.textContent="💰 證券儲值申請";m.classList.add("show")}
function closeDeposit(){document.getElementById("deposit-modal")?.classList.remove("show")}
async function submitDeposit(){try{const amount=Number(document.getElementById("deposit-amount")?.value),accountId=uid();if(!accountId)return toast("請先完成 Google 登入，再申請儲值");if(!Number.isFinite(amount)||amount<=0)return toast("請輸入有效儲值金額");const s=await get(ref(db,"depositRequests"));let dup=false;if(s.exists())s.forEach(c=>{const r=c.val();if(r?.accountId===accountId&&r?.status==="pending")dup=true});if(dup)return toast("你已有一筆待審核的儲值申請");await set(push(ref(db,"depositRequests")),{accountId,uid:accountId,amount,status:"pending",createdAt:Date.now(),createdBy:accountId});closeDeposit();toast(`儲值申請 ${amount.toLocaleString()} 已送出，等待後臺審核`)}catch(e){console.error("儲值申請失敗",e);toast("儲值申請失敗："+(e?.message||"未知錯誤"))}}
async function submitIPO(code){try{const accountId=uid();if(!accountId)return toast("請先完成 Google 登入");const s=await get(ref(db,"companies"));const cm=map(s.exists()?s.val():{});const company=cm[code]||Object.values(cm).find(c=>String(c?.code).toUpperCase()===String(code).toUpperCase());if(!company)return toast("找不到這家公司");if(company.owner&&String(company.owner)!==String(accountId))return toast("你不是這家公司的負責人");if(company.listed)return toast("這家公司已經上市");if(company.ipoStatus==="審核中")return toast("IPO 已在審核中");if(Number(company.capital)<10000000)return toast("註冊資本不足 ¥10,000,000");const p=await get(ref(db,"ipoRequests"));let dup=false;if(p.exists())p.forEach(c=>{const r=c.val();if(String(r?.code).toUpperCase()===String(company.code).toUpperCase()&&String(r?.owner)===String(accountId)&&r?.status==="pending")dup=true});if(dup)return toast("這家公司已有待審核的 IPO 申請");if(!confirm(`確定申請「${company.name}」IPO？\n\n股票代號：${company.code}\n註冊資本：¥${Number(company.capital).toLocaleString()}\n\n送出後必須由明月證券管理後臺核准。`))return;await set(push(ref(db,"ipoRequests")),{companyId:company.id||`${company.code}-COMPANY`,code:company.code,companyName:company.name,shortName:company.shortName||company.name,capital:Number(company.capital||0),owner:accountId,status:"pending",createdAt:Date.now(),createdBy:accountId});await set(ref(db,`companies/${company.code}/ipoStatus`),"審核中");await set(ref(db,`companies/${company.code}/ipoAppliedAt`),new Date().toLocaleString("zh-TW"));toast("IPO 申請已送出，等待管理員審核");if(typeof window.showPage==="function")window.showPage("company")}catch(e){console.error("IPO 申請失敗",e);toast("IPO 申請失敗："+(e?.message||"未知錯誤"))}}
async function publishApprovedIPO(request){if(!request?.code||request.status!=="approved")return;const code=String(request.code).trim().toUpperCase();const cs=await get(ref(db,"companies"));if(!cs.exists())throw new Error("Firebase 找不到 companies 資料");const cm=map(cs.val());let company=cm[code]||Object.values(cm).find(c=>String(c?.code).toUpperCase()===code);if(!company)throw new Error(`找不到公司：${code}`);company={...company};if(company.listed===true&&company.ipoStatus==="已上市")return;company.listed=true;company.ipoStatus="已上市";company.status="上市公司";company.listedAt=company.listedAt||new Date().toLocaleString("zh-TW");const ss=await get(ref(db,"stocks"));const sm=map(ss.exists()?ss.val():{});let stock=sm[code]||Object.values(sm).find(s=>String(s?.id).toUpperCase()===code);if(!stock){const capital=Number(company.capital||request.capital||0);if(!Number.isFinite(capital)||capital<=0)throw new Error("公司註冊資本無效");const shares=Math.max(1000000,Math.floor(capital/10));const price=Number((capital/shares).toFixed(2));stock={id:code,name:company.shortName||company.name,company:company.name,companyCode:code,companyId:company.id||`${code}-COMPANY`,industry:company.industry||"其他",type:"上市公司",price,previous:price,volume:0,capital,shares,listed:true,listedAt:company.listedAt,createdAt:Date.now()}}else{stock={...stock,company:company.name,companyCode:code,companyId:company.id||stock.companyId||`${code}-COMPANY`,industry:company.industry||stock.industry||"其他",type:"上市公司",listed:true,listedAt:company.listedAt}}await set(ref(db,`companies/${code}`),company);await set(ref(db,`stocks/${code}`),stock);localStorage.setItem("mingyue_companies_v42",JSON.stringify(list({...cm,[code]:company})));localStorage.setItem("mingyue_stocks_v42",JSON.stringify(list({...sm,[code]:stock})));toast(`🎉 ${company.shortName||company.name} 已正式上市，股票 ${code} 已加入行情`);if(typeof window.renderCompanies==="function")window.renderCompanies();if(typeof window.renderMarket==="function")window.renderMarket();if(typeof window.updateAllVisible==="function")window.updateAllVisible()}
function watchApprovedIPO(){onValue(ref(db,"ipoRequests"),s=>{if(!s.exists())return;s.forEach(c=>{const r=c.val();if(r?.status==="approved")publishApprovedIPO(r).catch(e=>console.error("核准 IPO 發布失敗",e))})},e=>console.error("IPO 審核同步失敗",e))}
function install(){window.openDepositModal=openDeposit;window.openDeposit=openDeposit;window.deposit=submitDeposit;window.depositMoney=submitDeposit;window.confirmDeposit=submitDeposit;window.applyIPO=submitIPO;window.approveIPO=()=>toast("IPO 必須由管理後臺核准");window.MingyueIPO=Object.freeze({submit:submitIPO,publishApproved:publishApprovedIPO})}
install();window.addEventListener("load",install);setTimeout(install,500);setTimeout(install,1500);onAuthStateChanged(auth,u=>{if(u){localStorage.setItem("mingyue_current_google_uid",u.uid);localStorage.setItem("mingyue_active_account_id",u.uid)}});watchApprovedIPO();console.log("明月證券 v4.4.1 Approval Bridge 已載入");
