import {initializeApp,getApps} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import {getAuth} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import {getFunctions,httpsCallable} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-functions.js";

const config={apiKey:"AIzaSyDWDaEZoZPwBe7wZX0aiDAGqs4b_EAkfgM",authDomain:"mingyue-stock.firebaseapp.com",databaseURL:"https://mingyue-stock-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"mingyue-stock",storageBucket:"mingyue-stock.firebasestorage.app",messagingSenderId:"774198660845",appId:"1:774198660845:web:93f4a725b6303aae9f86e4"};
const app=getApps().length?getApps()[0]:initializeApp(config);const auth=getAuth(app);const functions=getFunctions(app,"asia-southeast1");const createDepositRequest=httpsCallable(functions,"createDepositRequest");const createWithdrawal=httpsCallable(functions,"createWithdrawal");
const toast=m=>window.showToast?window.showToast(m):alert(m);
function ensureUI(){
 document.querySelectorAll('[onclick*="openDepositModal"]').forEach(b=>{b.removeAttribute("onclick");b.addEventListener("click",openDepositModal);});
 if(!document.getElementById("finance-actions")){const card=document.createElement("div");card.id="finance-actions";card.className="section-card";card.innerHTML='<div class="section-title">💰 證券資金</div><div class="section-subtitle">儲值與提領均需金融後台審核</div><div style="display:flex;gap:8px;margin-top:12px;flex-wrap:wrap"><button class="primary-button" id="finance-deposit">＋ 儲值申請</button><button class="primary-button" id="finance-withdraw">－ 提領申請</button></div><div id="finance-status" class="section-subtitle" style="margin-top:10px"></div>';const p=document.getElementById("page-portfolio");p?.insertBefore(card,p.firstChild);document.getElementById("finance-deposit").onclick=openDepositModal;document.getElementById("finance-withdraw").onclick=openWithdrawalModal;}
}
function modal(id,title,desc,submit){let old=document.getElementById(id);if(old)old.remove();const m=document.createElement("div");m.id=id;m.className="modal show";m.innerHTML=`<div class="modal-box"><div class="modal-header"><div><h3>${title}</h3><p>${desc}</p></div><button class="modal-close" type="button">×</button></div><div class="form-group"><label>金額</label><input id="${id}-amount" type="number" min="1" step="0.01" placeholder="例如 10000"></div><button id="${id}-submit" class="primary-button full" type="button">送出申請</button></div>`;document.body.appendChild(m);m.querySelector(".modal-close").onclick=()=>m.remove();m.addEventListener("click",e=>{if(e.target===m)m.remove();});m.querySelector("#"+id+"-submit").onclick=()=>submit(Number(m.querySelector("input").value),m);setTimeout(()=>m.querySelector("input")?.focus(),30);}
function openDepositModal(){modal("finance-deposit-modal","💰 證券帳戶儲值","送出後會進入金融後台審核，核准後才增加餘額。",async(amount,m)=>{if(!amount||amount<=0)return toast("請輸入有效金額");try{if(!auth.currentUser)return toast("請先完成 Google 登入");const r=await createDepositRequest({amount});m.remove();toast("儲值申請已送出，等待後台審核");}catch(e){toast(e?.message||"儲值申請失敗");}});}
function openWithdrawalModal(){modal("finance-withdraw-modal","－ 證券帳戶提領","金額會先凍結；只有後台核准後才完成提領。",async(amount,m)=>{if(!amount||amount<=0)return toast("請輸入有效金額");try{if(!auth.currentUser)return toast("請先完成 Google 登入");await createWithdrawal({amount});m.remove();toast("提領申請已送出，金額已凍結等待審核");}catch(e){toast(e?.message||"提領申請失敗");}});}
window.openDepositModal=openDepositModal;window.openWithdrawalModal=openWithdrawalModal;window.depositMoney=()=>openDepositModal();window.withdrawMoney=()=>openWithdrawalModal();
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(ensureUI,350),{once:true});else setTimeout(ensureUI,350);
