/* =========================================================
   明月證券 v4.4
   Plugin Data Adapter - Google UID Bootstrap + Approval Bridge
   ========================================================= */
import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getAuth, onAuthStateChanged, setPersistence, browserLocalPersistence } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { getDatabase, ref, get, set, update } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js";
const firebaseConfig={apiKey:"AIzaSyDWDaEZoZPwBe7wZX0aiDAGqs4b_EAkfgM",authDomain:"mingyue-stock.firebaseapp.com",databaseURL:"https://mingyue-stock-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"mingyue-stock",storageBucket:"mingyue-stock.firebasestorage.app",messagingSenderId:"774198660845",appId:"1:774198660845:web:93f4a725b6303aae9f86e4",measurementId:"G-Z7F6N0ZJYJ"};
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);
const PATHS=["users","stocks","companies","news","ipo","portfolios","transactions","historyData","authUsers","depositRequests","ipoRequests"];
const CACHE_KEYS={users:"mingyue_user_v43",stocks:"mingyue_stocks_v43",companies:"mingyue_companies_v43",news:"mingyue_news_v43",portfolios:"mingyue_portfolio_v43",transactions:"mingyue_transactions_v43",historyData:"mingyue_history_v43"};
function validKey(key){return PATHS.includes(String(key))}function getCurrentUid(){return auth.currentUser?.uid||window.MingyueAuth?.user?.uid||localStorage.getItem("mingyue_current_google_uid")||null}function getExternalPlugin(){return window.MingyueExternalPlugin||window.mingyueExternalPlugin||window.MingyuePlugin||window.mingyuePlugin||null}
async function externalRead(key){const p=getExternalPlugin();if(!p)return undefined;try{if(typeof p.read==="function")return await p.read(key);if(typeof p.get==="function")return await p.get(key);if(typeof p.readData==="function")return await p.readData(key);if(typeof p.getData==="function")return await p.getData(key)}catch(e){console.warn("外掛讀取失敗",key,e)}return undefined}
async function externalWrite(key,value){const p=getExternalPlugin();if(!p)return false;try{if(typeof p.write==="function"){await p.write(key,value);return true}if(typeof p.set==="function"){await p.set(key,value);return true}if(typeof p.writeData==="function"){await p.writeData(key,value);return true}}catch(e){console.warn("外掛寫入失敗",key,e)}return false}
async function externalReadAll(){const p=getExternalPlugin();if(!p)return undefined;try{if(typeof p.readAll==="function")return await p.readAll();if(typeof p.getAll==="function")return await p.getAll()}catch(e){console.warn("外掛全資料讀取失敗",e)}return undefined}
async function externalWriteMany(data){const p=getExternalPlugin();if(!p)return false;try{if(typeof p.writeMany==="function"){await p.writeMany(data||{});return true}}catch(e){console.warn("外掛批次寫入失敗",e)}return false}
function filterPaths(data){const result={};for(const key of PATHS)if(Object.prototype.hasOwnProperty.call(data||{},key))result[key]=data[key];return result}
function cacheData(data){try{const uid=getCurrentUid();for(const key of PATHS){if(!Object.prototype.hasOwnProperty.call(data||{},key))continue;const value=data[key],cacheKey=CACHE_KEYS[key];if(!cacheKey)continue;if(["users","portfolios","transactions"].includes(key)){const account=uid?value?.[uid]:null;if(account!==undefined&&account!==null)localStorage.setItem(cacheKey,JSON.stringify(account))}else localStorage.setItem(cacheKey,JSON.stringify(value))}}catch(e){console.warn("LocalStorage fallback 寫入失敗",e)}}
async function bootstrapLegacyV42(user){if(!user?.uid)return null;const uid=String(user.uid);let account=null;try{const snap=await get(ref(db,`users/${uid}`));account=snap.exists()?snap.val():null}catch(e){console.warn("Google UID 帳號預載入失敗",e)}const existing=account&&typeof account==="object"?account:{};const balance=Number.isFinite(Number(existing.balance))?Number(existing.balance):0;const legacyUser={...existing,accountId:uid,googleUid:uid,name:existing.name||user.displayName||user.email||"Google 使用者",email:existing.email||user.email||"",photoURL:existing.photoURL||user.photoURL||"",balance};localStorage.setItem("mingyue_current_google_uid",uid);localStorage.setItem("mingyue_active_account_id",uid);localStorage.setItem("mingyue_user_v42",JSON.stringify(legacyUser));if(!account)await update(ref(db),{[`users/${uid}`]:{...legacyUser,createdAt:Date.now(),lastLoginAt:Date.now()},[`portfolios/${uid}`]:{},[`transactions/${uid}`]:[]});else await update(ref(db),{[`users/${uid}/lastLoginAt`]:Date.now()});return legacyUser}
async function read(key){if(!validKey(key))throw new Error("不允許的資料路徑："+key);const external=await externalRead(key);if(external!==undefined&&external!==null)return external;try{const s=await get(ref(db,key));return s.exists()?s.val():null}catch(e){console.warn("Firebase 讀取失敗",key,e);return null}}
async function write(key,value){if(!validKey(key))throw new Error("不允許的資料路徑："+key);const externalOK=await externalWrite(key,value);try{await set(ref(db,key),value)}catch(e){if(!externalOK)throw e;console.warn("Firebase 鏡像失敗",key,e)}return true}
async function writeMany(data){const patch=filterPaths(data);if(!Object.keys(patch).length)return[];const externalOK=await externalWriteMany(patch);try{await update(ref(db),patch)}catch(e){if(!externalOK)throw e;console.warn("Firebase 批次鏡像失敗",e)}return Object.keys(patch)}
async function readAll(){const external=await externalReadAll();if(external&&typeof external==="object"&&Object.keys(external).length){cacheData(external);return external}try{const s=await get(ref(db));const data=s.exists()?s.val():{};cacheData(data);return data}catch(e){console.warn("Firebase 全資料讀取失敗",e);return{}}}
async function preload(){const data=await readAll();console.log(data&&Object.keys(data).length?"明月證券 v4.4：資料已預載入":"明月證券 v4.4：沒有遠端資料");return data}
window.MingyueDataPlugin=Object.freeze({version:"4.4",paths:Object.freeze([...PATHS]),read,write,writeMany,readAll,preload,getCurrentUid,isReady:true});window.MingyueDataAdapter=window.MingyueDataPlugin;window.MINGYUE_V433=true;
await setPersistence(auth,browserLocalPersistence).catch(e=>console.warn("Firebase Auth 持久化設定失敗",e));
await new Promise(resolve=>{let settled=false;const finish=()=>{if(!settled){settled=true;resolve()}};const unsubscribe=onAuthStateChanged(auth,async user=>{try{if(user){await bootstrapLegacyV42(user);window.MINGYUE_CURRENT_UID=user.uid;window.MINGYUE_ACCOUNT_ID=user.uid}}catch(e){console.warn("Google UID bootstrap 失敗",e)}finally{unsubscribe();finish()}});setTimeout(finish,5000)});
console.log("明月證券 v4.4 Plugin Data Adapter 已載入");await preload();
try{await import("./google-auth.js?v=4.4");window.MINGYUE_V43=true;console.log("明月證券 v4.4 Google Account 模組已接入")}catch(e){window.MINGYUE_V43=false;console.warn("Google Account 模組載入失敗",e)}
try{await import("./approval-bridge.js?v=4.4");window.MINGYUE_V44=true;console.log("明月證券 v4.4 儲值/IPO 審核模組已接入")}catch(e){window.MINGYUE_V44=false;console.warn("v4.4 Approval Bridge 載入失敗",e)}
try{await import("./stock-sync.js?v=4.4");window.MINGYUE_STOCK_SYNC=true;console.log("明月證券 v4.4 上市股票同步模組已接入")}catch(e){window.MINGYUE_STOCK_SYNC=false;console.warn("v4.4 Stock Sync 模組載入失敗",e)}
try{await import("./company-status-sync.js?v=4.4");window.MINGYUE_COMPANY_STATUS_SYNC=true;console.log("明月證券 v4.4 公司上市狀態同步模組已接入")}catch(e){window.MINGYUE_COMPANY_STATUS_SYNC=false;console.warn("v4.4 Company Status Sync 模組載入失敗",e)}
try{await import("./deposit-fix.js?v=4.4");window.MINGYUE_DEPOSIT_FIX=true;console.log("明月證券 v4.4 Firebase 儲值模組已接入")}catch(e){window.MINGYUE_DEPOSIT_FIX=false;console.warn("v4.4 Deposit Fix 模組載入失敗",e)}
