/* 明月證券 v4.3.4
   Wallet deposit request / review bridge
   Firebase path: depositRequests
*/
(function () {
  "use strict";
  const firebaseConfig={apiKey:"AIzaSyDWDaEZoZPwBe7wZX0aiDAGqs4b_EAkfgM",authDomain:"mingyue-stock.firebaseapp.com",databaseURL:"https://mingyue-stock-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"mingyue-stock",storageBucket:"mingyue-stock.firebasestorage.app",messagingSenderId:"774198660845",appId:"1:774198660845:web:93f4a725b6303aae9f86e4"};
  const ADMIN_EMAILS=["edisonkuo1030@gmail.com"];
  let appPromise;
  async function getFirebase(){if(!appPromise){appPromise=Promise.all([import("https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js"),import("https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js"),import("https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js")]).then(([fa,fau,fdb])=>{const app=fa.getApps().length?fa.getApps()[0]:fa.initializeApp(firebaseConfig);return{auth:fau.getAuth(app),db:fdb.getDatabase(app),ref:fdb.ref,get:fdb.get,push:fdb.push,set:fdb.set,update:fdb.update};});}return appPromise;}
  function uid(){return window.MingyueAuthBridge?.getUid?.()||window.MINGYUE_CURRENT_UID||null;}
  function accountId(){return window.MingyueAuthBridge?.getAccountId?.()||window.MINGYUE_ACCOUNT_ID||uid();}
  function currentUser(){return window.MingyueAuthBridge?.getUser?.()||window.MingyueAuth?.user||null;}
  function isAdminUser(user){return !!user&&ADMIN_EMAILS.includes(String(user.email||"").toLowerCase());}
  async function submitDeposit(){const amountEl=document.getElementById("deposit-amount"),amount=Number(amountEl?.value);if(!Number.isFinite(amount)||amount<=0)return window.showToast?.("請輸入有效儲值金額");const userUid=uid();if(!userUid)return window.showToast?.("請先完成 Google 實名認證");try{const fb=await getFirebase(),user=fb.auth.currentUser||currentUser(),requestRef=fb.push(fb.ref(fb.db,"depositRequests")),request={uid:String(userUid),accountId:String(accountId()||userUid),email:user?.email||"",displayName:user?.displayName||"",amount:Number(amount),source:"wallet",status:"pending",createdAt:Date.now()};await fb.set(requestRef,request);amountEl.value="";window.closeModal?.("deposit-modal");window.showToast?.("儲值申請已送出，等待管理員審核");window.dispatchEvent(new CustomEvent("mingyue-deposit-submitted",{detail:{id:requestRef.key,...request}}));}catch(error){console.error("儲值申請失敗",error);window.showToast?.("儲值申請失敗，請稍後再試");}}
  async function listDeposits(){const fb=await getFirebase(),snap=await fb.get(fb.ref(fb.db,"depositRequests"));return snap.exists()?(snap.val()||{}):{};}
  async function reviewDeposit(id,approved){const user=currentUser();if(!isAdminUser(user))return{ok:false,error:"沒有管理員權限"};const fb=await getFirebase(),requestRef=fb.ref(fb.db,"depositRequests/"+id),snap=await fb.get(requestRef);if(!snap.exists())return{ok:false,error:"找不到儲值申請"};const request=snap.val()||{};if(request.status&&request.status!=="pending")return{ok:false,error:"這筆申請已經處理過"};const amount=Number(request.amount);if(!Number.isFinite(amount)||amount<=0)return{ok:false,error:"申請金額無效"};if(approved){const targetId=String(request.accountId||request.uid||"");if(!targetId)return{ok:false,error:"申請缺少帳戶 ID"};const userRef=fb.ref(fb.db,"users/"+targetId),userSnap=await fb.get(userRef),oldUser=userSnap.exists()?(userSnap.val()||{}):{},oldBalance=Number(oldUser.balance)||0;await fb.update(userRef,{balance:oldBalance+amount,lastDepositAt:Date.now()});}const result={status:approved?"approved":"rejected",reviewedAt:Date.now(),reviewedBy:user.email||""};await fb.update(requestRef,result);return{ok:true,request:{...request,...result}};}
  window.MingyueWalletReview=Object.freeze({submitDeposit,listDeposits,reviewDeposit,isAdmin:()=>isAdminUser(currentUser())});window.depositMoney=submitDeposit;window.confirmDeposit=submitDeposit;console.log("明月證券 v4.3.4 Wallet Review Bridge 已載入");
})();
